Use DrillingInfo 

if not exists (select * 
    from INFORMATION_SCHEMA.TABLES   
    where TABLE_SCHEMA = N'dbo' and TABLE_NAME = N'ProducingEntityStats') 
begin
	
create table ProducingEntityStats (
	EntityStatID int primary key identity,
	FullGasEur numeric(18) null,
	Decl12MoWtr numeric(15,4) null,
	BeGasDeltaEurPct numeric(18,2) null,
	BoePracIp numeric(15,4) null,
	FullBFactor numeric(18,2) null,
	First6Liq numeric(15,4) null,
	FullFinalRate numeric(18,2) null,
	Decl60MoLiq numeric(15,4) null,
	PeakGasMonthNo numeric(5) null,
	YieldLatestMo numeric(15,4) null,
	First6Gas numeric(15,4) null,
	FullOilEur numeric(18) null,
	GasYear numeric(14,4) null,
	PeakDailyLiqMonthNo numeric(5) null,
	PeakGas numeric(14,4) null,
	CfgedCurRate numeric(15,4) null,
	GasDaily numeric(9) null,
	BeGasDeltaEur numeric(18) null,
	First24Wtr numeric(15,4) null,
	FirstLiq numeric(9) null,
	LiqMaxDaily numeric(15,4) null,
	MmcfgeCum numeric(15,4) null,
	BeInitialRate numeric(18) null,
	GasMaxDaily numeric(15,4) null,
	Gor2ndMo numeric(22,2) null,
	LiqPracIpDaily numeric(15,4) null,
	PeakBoe numeric(15,4) null,
	PeakBoeMonth datetime null,
	Yield numeric(15,4) null,
	LatestLiq numeric(9) null,
	LatestTestDate datetime null,
	BebFactor numeric(18,2) null,
	Decl60MoWtr numeric(15,4) null,
	MaxWtrDaily numeric(15,4) null,
	PdenGranularity varchar(50) null,
	LatestFlowRes numeric(14,4) null,
	PeakDailyLiqMonth date null,
	PeakLiqMonthNo numeric(5) null,
	UpdatedDate datetime null,
	Decl3MoLiq numeric(15,4) null,
	First60Liq numeric(15,4) null,
	First6Wtr numeric(15,4) null,
	FirstProdDate date null,
	MaxActvWells numeric(10) null,
	PeakMmcfge numeric(15,4) null,
	WtrCum numeric(15,4) null,
	First12Liq numeric(9) null,
	First60Gas numeric(15,4) null,
	GorLatestMo numeric(22,2) null,
	Prior12Wtr numeric(9) null,
	BeInitialDecline numeric(18,6) null,
	First12Boe numeric(15,4) null,
	First6Boe numeric(15,4) null,
	GasCum numeric(14,4) null,
	BeEndDate date null,
	PeakMmcfgeMonth date null,
	FullEndDate date null,
	FullOilRrr numeric(18) null,
	First24Gas numeric(15,4) null,
	PeakGasDaily numeric(15,4) null,
	LiqCum numeric(15,4) null,
	Decl12MoLiq numeric(15,4) null,
	Yield2ndMo numeric(15,4) null,
	LiqYear numeric(14,4) null,
	PeakLiq numeric(14,4) null,
	PeakLiqMonth date null,
	PriorGasCum numeric(14,4) null,
	WtrDaily numeric(15,4) null,
	Decl12MoGas numeric(15,4) null,
	GasPracIpDaily numeric(15,4) null,
	LastProdDate date null,
	FullGasRrr numeric(18) null,
	Prior12Liq numeric(9) null,
	First12Mmcfge numeric(15,4) null,
	IsDeleted int null,
	LatestWhsip numeric(14,4) null,
	LiqDaily numeric(9) null,
	First24Boe numeric(15,4) null,
	FirstWtr numeric(9) null,
	CfgedPracIp numeric(15,4) null,
	First6Mmcfge numeric(15,4) null,
	WtrYear numeric(14,4) null,
	Decl24MoWtr numeric(15,4) null,
	EurCalcDate date null,
	Decl3MoGas numeric(15,4) null,
	BeOilRrr numeric(18) null,
	First24Mmcfge numeric(15,4) null,
	PriorWtrCum numeric(14,4) null,
	First12Wtr numeric(14) null,
	LatestGas numeric(14,4) null,
	Decl24MoGas numeric(15,4) null,
	CreatedDate datetime null,
	DeletedDate datetime null,
	BeOilDeltaEurPct numeric(18,2) null,
	BoeCum numeric(15,4) null,
	LatestWtr numeric(14) null,
	PeakDailyGasMonthNo numeric(5) null,
	PeakLiqDaily numeric(15,4) null,
	BeOilDeltaEur numeric(18) null,
	GorCum numeric(22,2) null,
	LatestWcnt numeric(4) null,
	First60Wtr numeric(15,4) null,
	Prior12Gas numeric(9) null,
	BeGasEur numeric(18) null,
	BeOilEur numeric(18) null,
	BcfgeCum numeric(15,4) null,
	First60Boe numeric(15,4) null,
	EntityId int null unique,
	BeGasRrr numeric(18) null,
	PeakDailyGasMonth date null,
	PeakGasMonth date null,
	Decl24MoLiq numeric(15,4) null,
	BeFinalRate numeric(18) null,
	First12Gas numeric(14) null,
	First60Mmcfge numeric(15,4) null,
	PeakBoeMonthNo numeric(5) null,
	PeakMmcfgeMonthNo numeric(5) null,
	EurPrimaryProduct varchar(15) null,
	FullInitialDecline numeric(18,6) null,
	FirstGas numeric(14,4) null,
	MonthsProduced numeric(6) null,
	First24Liq numeric(15,4) null,
	Gor numeric(15,4) null,
	Decl60MoGas numeric(15,4) null,
	PriorLiqCum numeric(14,4) null,
	Decl3MoWtr numeric(15,4) null,
	BeGasBfactor float null,
	BeGasEndDate datetime null,
	BeGasFinalRate float null,
	BeGasInitialDate datetime null,
	BeGasInitialDecline float null,
	BeGasInitialRate float null,
	BeGasMonths float null,
	BeOilBfactor float null,
	BeOilEndDate datetime null,
	BeOilFinalRate float null,
	BeOilInitialDecline float null,
	BeOilInitialRate float null,
	BeOilMonths float null,
	FullGasBfactor float null,
	FullGasEndDate datetime null,
	FullGasFinalRate float null,
	FullGasInitialDecline float null,
	FullGasMonths float null,
	FullGasInitialRate float null,
	FullOilBfactor float null,
	FullOilEndDate datetime null,
	FullOilFinalRate float null,
	FullOilInitialDecline float null,
	FullOilInitialRate float null,
	FullOilMonths float null,
	IsGasDcaProxied bit null,
	IsOilDcaProxied bit null,
	Mi4AddDtTm datetime default GETDATE(),
	Mi4LastUpdateDtTm datetime null)

									   

end

begin

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].ProducingEntityStats') AND name = N'IX_ProducingEntityStats_UpdatedDate') CREATE NONCLUSTERED INDEX IX_ProducingEntityStats_UpdatedDate ON DrillingInfo.dbo.ProducingEntityStats (UpdatedDate)

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].ProducingEntityStats') AND name = N'IX_ProducingEntityStats_DeletedDate') CREATE NONCLUSTERED INDEX IX_ProducingEntityStats_DeletedDate ON DrillingInfo.dbo.ProducingEntityStats (DeletedDate)

end