Use DrillingInfo 

if not exists (select * 
    from INFORMATION_SCHEMA.TABLES   
    where TABLE_SCHEMA = N'dbo' and TABLE_NAME = N'Transactions') 
begin

create table Transactions(
	Mi4TransactionID int primary key identity,
	AcreageReportedBy varchar(max) null,
	AcresGross float null,
	AcresGrossUndeveloped float null,
	AcresNet float null,
	AcresNetDeveloped float null,
	AcresNetUndeveloped float null,
	AcresPercentHBP float null,
	BuyerTicker varchar(max) null,
	Buyers varchar(max) null,
	BuyersAsReported varchar(max) null,
	BuyersFinancialAdvisors varchar(max) null,
	BuyersHeadquarters varchar(max) null,
	BuyersLegalAdvisors varchar(max) null,
	BuyersPeerGroup varchar(max) null,
	CashFlowOrEBITDAComment varchar(max) null,
	CashFlowOrEBITDAMM float null,
	CashFlowOrEBITDAMultiple float null,
	CashFlowOrEBITDAMultipleComment varchar(max) null,
	Country varchar(max) null,
	CountyParish varchar(1000) null,
	CreatedDate datetime null,
	DIBasin varchar(max) null,
	DIClosingStory varchar(max) null,
	DINarrative varchar(max) null,
	DateAnnounced datetime null,
	DateClosed datetime null,
	DateEffective datetime null,
	DealHighlights varchar(max) null,
	DealStatus varchar(max) null,
	DealType varchar(max) null,
	DealValueCashMM float null,
	DealValueDebtMM float null,
	DealValueEquityMM float null,
	DealValueNetDebtAssumedMM float null,
	DealValueOtherMM float null,
	DeletedDate datetime null,
	DollarPer2PBOE float null,
	DollarPer2PMcfe float null,
	DollarPer3PBOE float null,
	DollarPer3PMcfe float null,
	DollarPerAcre float null,
	DollarPerContingentBOE float null,
	DollarPerContingentMcfe float null,
	DollarPerDailyBOE float null,
	DollarPerDailyMcfe float null,
	DollarPerLocation float null,
	DollarPerProvedBOE float null,
	DollarPerProvedMcfe float null,
	DrillingLocationsComment varchar(max) null,
	[Geometry] varchar(max) null,
	Headline varchar(max) null,
	Hydrocarbon varchar(max) null,
	Latitude float null,
	Longitude float null,
	MarketCommentary varchar(max) null,
	NumberOfDrillingLocationsNet int null,
	OnshoreOffshore varchar(max) null,
	OpNonOp varchar(max) null,
	OperatorCompanyName varchar(max) null,
	OperatorTicker varchar(max) null,
	PV102P float null,
	PV103P float null,
	PV10Comments varchar(max) null,
	PV10Contingent float null,
	PV10PD float null,
	PV10PD2 float null,
	PV10PDPercentOfProved float null,
	PV10PUD float null,
	PV10Possible float null,
	PV10Probable float null,
	PV10Proved float null,
	PremiumDiscount float null,
	PremiumDiscount30Day float null,
	PremiumDiscount30DayPriorAvg float null,
	PremiumDiscount60Day float null,
	PremiumDiscount60DayPriorAvg float null,
	PremiumDiscount90Day float null,
	PremiumDiscount90DayPriorAvg float null,
	PremiumDiscountOffer varchar(max) null,
	PremiumDiscountOfferDate datetime null,
	PremiumDiscountOfferPrice float null,
	PremiumDiscountPreDeal float null,
	PriceHenryHubSpotDollarPerMMbtu float null,
	PriceNYMEXGas12MStrpDolPerMMbtu float null,
	PriceNYMEXOil12MStrpDolPerBbl float null,
	PriceWTISpotDollarPerBbl float null,
	ProductionBOPD float null,
	ProductionComments varchar(max) null,
	ProductionMBOED float null,
	ProductionMMcfd float null,
	ProductionMMcfed float null,
	ProductionMbbld float null,
	ProductionNGLIncludedWithCrude bit null,
	ProductionNGLMbbld float null,
	ProductionPercentGas float null,
	ProductionPercentNGLs float null,
	ProductionPercentOil float null,
	ProductionPercentOilAndNGLs float null,
	ProductionReportedBy varchar(max) null,
	RByPProvedDeveloped float null,
	RByPProvedReserves float null,
	ReserveDataPublic bit null,
	Reserves2PBcf float null,
	Reserves2PBcfe float null,
	Reserves2PMMbbl float null,
	Reserves2PMMboe float null,
	Reserves2PNGLMMbbl float null,
	Reserves3PBcf float null,
	Reserves3PBcfe float null,
	Reserves3PMMbbl float null,
	Reserves3PMMboe float null,
	Reserves3PNGLMMbbl float null,
	ReservesComments varchar(max) null,
	ReservesContingentBcf float null,
	ReservesContingentMMbbl float null,
	ReservesContingentMMboe float null,
	ReservesContingentNGLMMbbl float null,
	ReservesNGLIncludedWithCrude bit null,
	ReservesPossibleBcf float null,
	ReservesPossibleMMbbl float null,
	ReservesPossibleMMboe float null,
	ReservesPossibleNGLMMbbl float null,
	ReservesProbableBcf float null,
	ReservesProbableMMbbl float null,
	ReservesProbableMMboe float null,
	ReservesProbableNGLMMbbl float null,
	ReservesProvedBcf float null,
	ReservesProvedBcfPercentProved float null,
	ReservesProvedBcfe float null,
	ReservesProvedDevelopdBcfPercntPD float null,
	ReservesProvedDevelopedBcf float null,
	ReservesProvedDevelopedBcfe float null,
	ReservesProvedDevelopedMMbbl float null,
	ReservesProvedDevelopedMMbblPrcntPD float null,
	ReservesProvedDevelopedMMboe float null,
	ReservesProvedDevelopedMMboePrcntPD float null,
	ReservesProvedDevelopedNGLMMbbl float null,
	ReservesProvedDevelopedNGLMMbblPrcntPD float null,
	ReservesProvedMMbbl float null,
	ReservesProvedMMbblPercentProved float null,
	ReservesProvedMMboe float null,
	ReservesProvedMMboePercentProved float null,
	ReservesProvedNGLMMbbl float null,
	ReservesProvedNGLMMbblPercntPrved float null,
	ReservesProvedPercentOil float null,
	ReservesProvedUndevelopedBcf float null,
	ReservesProvedUndevelopedMMbbl float null,
	ReservesProvedUndevelopedMMboe float null,
	ReservesProvedUndevelopedNGLMMbbl float null,
	ReservesReportedBy varchar(max) null,
	ReservoirEngineering varchar(max) null,
	ResourceType varchar(max) null,
	SellerTicker varchar(max) null,
	Sellers varchar(max) null,
	SellersAsReported varchar(max) null,
	SellersFinancialAdvisors varchar(max) null,
	SellersHeadquarters varchar(max) null,
	SellersLegalAdvisors varchar(max) null,
	SellersPeerGroup varchar(max) null,
	[State] varchar(1000) null,
	TransactionID int null,
	TransactionNotes varchar(max) null,
	USPlay varchar(max) null,
	USRegion varchar(max) null,
	USSubregion varchar(max) null,
	UpdatedDate datetime null,
	ValuationNotes varchar(max) null,
	Value2PMM float null,
	Value3PMM float null,
	ValueAcreageMM float null,
	ValueContingentMM float null,
	ValueDollarMM float null,
	ValueMMAsReported float null,
	ValueOtherMM float null,
	ValueProvedMM float null,
	Mi4AddDtTm datetime NULL default GETDATE(),
	Mi4LastUpdateDtTm datetime null)
				
end

begin

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].Transactions') AND name = N'IX_Transactions_UpdatedDate') CREATE NONCLUSTERED INDEX IX_Transactions_UpdatedDate ON DrillingInfo.dbo.Transactions (UpdatedDate)

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].Transactions') AND name = N'IX_Transactions_State') CREATE NONCLUSTERED INDEX IX_Transactions_State ON DrillingInfo.dbo.Transactions ([State])

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].Transactions') AND name = N'IX_Transactions_CountyParish') CREATE NONCLUSTERED INDEX IX_Transactions_CountyParish ON DrillingInfo.dbo.Transactions (CountyParish)

IF NOT EXISTS (SELECT * FROM DrillingInfo.sys.indexes WHERE object_id = OBJECT_ID(N'DrillingInfo.[dbo].Transactions') AND name = N'IX_Transactions_DeletedDate') CREATE NONCLUSTERED INDEX IX_Transactions_DeletedDate ON DrillingInfo.dbo.Transactions (DeletedDate)

end


